/**
 * Builds a single self-contained HTML dashboard (library/dashboard.html) from
 * the competitor library, product database, and threat analysis. The marketing
 * team opens it in any browser — searchable, offline, no server.
 *
 * Data is embedded as JSON and rendered client-side; JSON values are escaped,
 * never injected as raw HTML.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const LIB_DIR = join(HERE, '..', 'library');

const PAGE = (dataJson, generatedAt) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Suterra — Competitive Intelligence Library</title>
<style>
  :root {
    --bg:#f8fafc; --card:#fff; --primary:#2563eb; --green:#22c55e; --red:#ef4444;
    --amber:#f59e0b; --text:#1f2937; --muted:#6b7280; --border:#e5e7eb;
    --font: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  }
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:var(--font); background:var(--bg); color:var(--text); line-height:1.5; }
  .wrap { max-width:1080px; margin:0 auto; padding:24px 20px 60px; }
  header { display:flex; align-items:baseline; justify-content:space-between; flex-wrap:wrap; gap:8px; margin-bottom:4px; }
  h1 { font-size:22px; font-weight:600; letter-spacing:-0.01em; }
  .sub { font-size:13px; color:var(--muted); margin-bottom:20px; }
  .stats { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:20px; }
  .stat { background:var(--card); border:1px solid var(--border); border-radius:12px; padding:12px 16px; flex:1; min-width:140px; }
  .stat b { display:block; font-size:24px; font-weight:600; }
  .stat span { font-size:12px; color:var(--muted); }
  .stat.threat b { color:var(--red); }
  input { width:100%; padding:11px 14px; font:inherit; font-size:14px; background:var(--card);
    border:1px solid var(--border); border-radius:12px; outline:none; margin-bottom:20px; }
  input:focus { border-color:var(--primary); box-shadow:0 0 0 3px rgba(37,99,235,.18); }
  .card { background:var(--card); border:1px solid var(--border); border-radius:16px; padding:18px 20px; margin-bottom:14px;
    box-shadow:0 1px 2px rgba(15,23,42,.04),0 2px 8px rgba(15,23,42,.06); }
  .card h2 { font-size:16px; font-weight:600; }
  .card h2 a { color:var(--primary); text-decoration:none; font-size:12px; font-weight:500; margin-left:8px; }
  .notes { font-size:12.5px; color:var(--muted); margin:4px 0 12px; }
  .section-label { font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:var(--muted); margin:14px 0 6px; font-weight:600; }
  .pill { display:inline-block; font-size:11px; padding:2px 8px; border-radius:999px; margin:0 4px 4px 0; border:1px solid var(--border); }
  .prod { font-size:13px; padding:6px 0; border-bottom:1px solid var(--border); }
  .prod:last-child { border-bottom:none; }
  .prod .meta { color:var(--muted); font-size:12px; }
  .threat { border-left:3px solid var(--red); padding:8px 12px; margin:6px 0; background:#fef2f2; border-radius:0 8px 8px 0; font-size:13px; }
  .threat.overlap { border-left-color:var(--amber); background:#fffbeb; }
  .threat .tag { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.03em; margin-right:6px; }
  .threat.direct .tag { color:var(--red); }
  .threat.overlap .tag { color:var(--amber); }
  .finding { font-size:13px; padding:8px 0; border-bottom:1px solid var(--border); }
  .finding:last-child { border-bottom:none; }
  .finding a { color:var(--primary); text-decoration:none; word-break:break-all; }
  .cat { display:inline-block; font-size:10px; font-weight:600; padding:1px 7px; border-radius:6px; background:rgba(37,99,235,.08); color:var(--primary); margin-right:6px; }
  .empty { color:var(--muted); font-size:12.5px; font-style:italic; }
  footer { margin-top:24px; font-size:11px; color:var(--muted); text-align:center; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Competitive Intelligence Library</h1>
  </header>
  <div class="sub">Suterra · generated ${generatedAt} · an automated draft — verify findings before acting.</div>
  <div class="stats" id="stats"></div>
  <input id="q" type="text" placeholder="Search competitor, product, pest, active ingredient…" autofocus />
  <div id="list"></div>
  <footer>Generated by the Suterra Competitive Intelligence Agent.</footer>
</div>
<script>
const DATA = ${dataJson};
const CAT_LABELS = { new_product:"New product", pheromone:"Pheromone", attract_and_kill:"Attract & Kill", patent:"Patent", partnership:"Partnership", other:"Other" };
const el = (t) => document.createElement(t);
const text = (tag, cls, s) => { const e = el(tag); if (cls) e.className = cls; if (s) e.textContent = s; return e; };

const totals = DATA.reduce((a, c) => {
  a.products += c.products.length; a.findings += c.findings.length;
  a.direct += c.threats.filter(t => t.level==="direct").length;
  a.overlap += c.threats.filter(t => t.level==="overlap").length;
  return a;
}, { products:0, findings:0, direct:0, overlap:0 });

const stats = document.getElementById("stats");
const addStat = (n, label, cls) => { const s = text("div","stat"+(cls?" "+cls:"")); s.append(text("b",null,String(n)), text("span",null,label)); stats.append(s); };
addStat(DATA.length,"Competitors"); addStat(totals.products,"Tracked products");
addStat(totals.direct,"Direct threats","threat"); addStat(totals.findings,"Findings logged");

const buildCard = (c) => {
  const card = text("div","card"); card.dataset.blob = c._blob;
  const h2 = text("h2", null, c.competitor);
  const link = el("a"); link.href = c.website; link.target = "_blank"; link.textContent = "website ↗"; h2.append(link);
  card.append(h2);
  if (c.notes) card.append(text("div","notes", c.notes));

  if (c.threats.length) {
    card.append(text("div","section-label","Threat overlap vs Suterra"));
    for (const t of c.threats) {
      const d = text("div","threat "+t.level);
      d.append(text("span","tag", t.level==="direct" ? "Direct" : "Overlap"));
      d.append(document.createTextNode(
        t.product+" targets "+t.pest+" ("+t.country+") — overlaps Suterra "+t.against +
        (t.level==="direct" ? " in the same market" : "")));
      card.append(d);
    }
  }

  card.append(text("div","section-label","Tracked products ("+c.products.length+")"));
  if (c.products.length) {
    for (const p of c.products) {
      const d = text("div","prod");
      d.append(text("strong",null,p.product||"—"));
      const meta = [p.productType, p.pest, p.country].filter(Boolean).join(" · ");
      if (meta) d.append(text("div","meta", meta));
      if (p.activeIngredients) d.append(text("div","meta", p.activeIngredients));
      card.append(d);
    }
  } else card.append(text("div","empty","No products on file yet."));

  card.append(text("div","section-label","Findings logged ("+c.findings.length+")"));
  if (c.findings.length) {
    for (const f of c.findings) {
      const d = text("div","finding");
      d.append(text("span","cat", CAT_LABELS[f.category]||"Other"));
      d.append(document.createTextNode(f.title+" "));
      if (f.summary) d.append(text("div","meta", f.summary));
      if (f.url) { const a = el("a"); a.href=f.url; a.target="_blank"; a.textContent=f.url; d.append(a); }
      card.append(d);
    }
  } else card.append(text("div","empty","No findings logged yet — run the agent to populate."));

  return card;
};

const list = document.getElementById("list");
const cards = DATA.map(c => { const card = buildCard(c); list.append(card); return card; });

document.getElementById("q").addEventListener("input", (e) => {
  const q = e.target.value.toLowerCase().trim();
  cards.forEach(card => { card.style.display = !q || card.dataset.blob.includes(q) ? "" : "none"; });
});
</script>
</body>
</html>`;

const searchBlob = (c) =>
  [
    c.competitor,
    c.notes,
    ...c.products.flatMap((p) => [p.product, p.pest, p.activeIngredients, p.country, p.productType]),
    ...c.findings.flatMap((f) => [f.title, f.summary, f.category]),
    ...c.threats.flatMap((t) => [t.product, t.pest, t.against]),
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();

/**
 * Renders and writes library/dashboard.html.
 * @returns {Promise<string>} the output path
 */
export const writeDashboard = async (entries, generatedAt) => {
  await mkdir(LIB_DIR, { recursive: true });
  const enriched = entries.map((c) => ({ ...c, _blob: searchBlob(c) }));
  const html = PAGE(JSON.stringify(enriched), generatedAt);
  const path = join(LIB_DIR, 'dashboard.html');
  await writeFile(path, html, 'utf8');
  return path;
};
